### PR TITLE
fix geojson:

### PR DESCRIPTION
**Pull request by Fil**
- rewind the geometries according to the d3-geo/leaflet custom
- fix coordinates below latitude -90

closes https://github.com/aourednik/historical-basemaps/issues/18

the script I used:
~~~js
function normalizeWindingOrder(geo) {
  switch (geo.type) {
    case "FeatureCollection":
      geo.features.forEach(normalizeWindingOrder);
      return geo;
    case "Feature":
      normalizeWindingOrder(geo.geometry);
      return geo;
    case "GeometryCollection":
      normalizeWindingOrder(geo.geometries);
      return geo;
    case "MultiPolygon":
      geo.coordinates.forEach(normalizePolygon);
      return geo;
    case "Polygon":
      normalizePolygon(geo.coordinates);
      return geo;
  }
  return geo;

  function normalizePolygon(coordinates) {
    coordinates.forEach((ring) =>
      ring.forEach((p) => {
        if (Math.abs(p[1]) > 90) p[1] = 90 * Math.sign(p[1]);
      })
    );
    coordinates.forEach(
      (ring, i) =>
        (d3.geoArea({ type: "Polygon", coordinates: [ring] }) >= 2 * Math.PI) ^
          !!i && ring.reverse()
    );
  }
}
~~~

### CODE REVIEW

**Comment by aourednik** [comment]
Many thanks!

**Comment by Fil** [comment]
A demo on how to use these files with Observable and Plot https://observablehq.com/@visionscarto/historical-boundaries

**Comment by Fil** [comment]
The first part makes sure that latitude is never above +90 or below -90.

The second part makes sure that none of the polygons are "reversed". I compute the area of each ring, and if it's greater than 2π I reverse it. For interior rings (holes, which have a position i>0), the check is reversed, since we want every hole to have an area > 2π (a hole's area is 4π minus the space that is "carved" by the hole).

**Comment by aourednik** [comment]
Thanks @Fil 

Turns out porting this to the R sf package is not immediately easy, but I managed to wrap your functions in a js file executable by a system call from R. Posting this here to keep a trace:

Call from R

```r
geojson <- file.path(path,to,geojson,file)
system(paste("/opt/homebrew/bin/node repair_geometries.js --file",geojson))
```

The JS script:

```javascript
// yarn add d3
// yarn add d3-geo

let d3 = {};
runapp();

async function runapp(){
  const fs = require('fs');
  d3 = await Promise.all([
    import("d3"),
    import("d3-geo")
  ]).then(d => Object.assign({}, ...d));
  let currentMapFile = process.argv[3];
  let data = fs.readFileSync(currentMapFile);
  data = JSON.parse(data);
  console.log(data);
  data.features = data.features.map(dat => normalizeWindingOrder(dat));
  fs.writeFileSync( currentMapFile, JSON.stringify(data));
}

function normalizeWindingOrder(geo) {
  switch (geo.type) {
    case "FeatureCollection":
      geo.features.forEach(normalizeWindingOrder);
      return geo;
    case "Feature":
      normalizeWindingOrder(geo.geometry);
      return geo;
    case "GeometryCollection":
      normalizeWindingOrder(geo.geometries);
      return geo;
    case "MultiPolygon":
      geo.coordinates.forEach(normalizePolygon);
      return geo;
    case "Polygon":
      normalizePolygon(geo.coordinates);
      return geo;
  }
  return geo;

  function normalizePolygon(coordinates) {
    coordinates.forEach((ring) =>
      ring.forEach((p) => {
        if (Math.abs(p[1]) > 90) p[1] = 90 * Math.sign(p[1]);
      })
    );
    coordinates.forEach(
      (ring, i) =>
        (d3.geoArea({ type: "Polygon", coordinates: [ring] }) >= 2 * Math.PI) ^
          !!i && ring.reverse()
    );
  }
}
```

**Pull request merged**
